"""create usersbodyprogress table

Revision ID: d7b205fa7108
Revises: 8bfcf3c2cc5a
Create Date: 2025-05-11 13:43:03.798929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b205fa7108'
down_revision: Union[str, None] = '8bfcf3c2cc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_body_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fat_percentage', sa.Float(), nullable=False),
    sa.Column('muscle_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_body_progress')
    # ### end Alembic commands ###
